### ISSUE TITLE
word_vec_300.bin这个哪里能拿到啊

### ISSUE THREAD

**Issue by porcobosso** [liuhuanyong/CrimeKgAssitant#1]
非常👍的项目，谢谢大神！

**Comment by liuhuanyong** [comment]
您好！
链接:https://pan.baidu.com/s/17w4pl7wCt45fmcOorqUgAA  密码:2utz

**Comment by porcobosso** [comment]
@liuhuanyong 谢谢^_^

**Comment by gitIsstudy** [comment]
您好，您提供的资源，百度网盘下载不下来怎么处理啊

**Comment by Holdwsq** [comment]
> 您好！
> 链接:https://pan.baidu.com/s/17w4pl7wCt45fmcOorqUgAA 密码:2utz

您好，您提供的资源，百度网盘下载不下来怎么处理啊

**Comment by wukong1024** [comment]
谢谢
