### ISSUE TITLE
你好，能提供一下 crime_classify 用的语料么？

### ISSUE THREAD

**Issue by BrikerMan** [liuhuanyong/CrimeKgAssitant#2]
如题，thanks

**Comment by huangdeyun** [comment]
很明显是用法研杯比赛的数据集，自己网上下载即可

**Comment by czhfibonacci** [comment]
请问question分类的标签是怎么得到的，数据的来源是？

**Comment by 1205469665** [comment]
请问这个里面的训练数据是从哪里找的?以及训练数据的代码有没有，

**Comment by herodialect** [comment]
同问，谢谢，2018法研杯数据https://github.com/thunlp/CAIL 我还没下下来
